# Generated by Django 5.1.2 on 2024-12-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('correo', models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=200, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='bedrooms ')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='bathrooms')),
                ('sqft_living', models.PositiveIntegerField(verbose_name='sqft_living')),
                ('sqft_lot', models.PositiveIntegerField(verbose_name='sqft_lot')),
                ('floors', models.PositiveIntegerField(verbose_name='floors')),
                ('waterfront', models.CharField(choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='waterfront')),
                ('view_c', models.PositiveIntegerField(default=0, verbose_name='view_C')),
                ('condition', models.PositiveIntegerField(default=3, verbose_name='condition')),
                ('grade', models.PositiveIntegerField(default=7, verbose_name='grade')),
                ('sqft_above', models.PositiveIntegerField(verbose_name='sqft_above')),
                ('sqft_basement', models.PositiveIntegerField(verbose_name='sqft_basement')),
                ('yr_built', models.PositiveIntegerField(verbose_name='yr_built')),
                ('yr_renovated', models.PositiveIntegerField(blank=True, null=True, verbose_name='yr_renovated')),
                ('zipcode', models.CharField(max_length=10, verbose_name='zipcode')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='analisis_casas_app.usuario')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
                'db_table': 'Casas',
            },
        ),
    ]
