# Generated by Django 5.1.2 on 2024-12-04 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_casas_app', '0002_alter_usuario_options_usuario_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casas',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='bathrooms',
            field=models.PositiveIntegerField(verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='bedrooms',
            field=models.PositiveIntegerField(verbose_name='Habitaciones'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='condition',
            field=models.PositiveIntegerField(default=3, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='floors',
            field=models.PositiveIntegerField(verbose_name='Pisos'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='grade',
            field=models.PositiveIntegerField(default=7, verbose_name='Calidad'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_above',
            field=models.PositiveIntegerField(verbose_name='Área sobre el suelo (sqft)'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_basement',
            field=models.PositiveIntegerField(default=0, verbose_name='Área del sótano (sqft)'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_living',
            field=models.PositiveIntegerField(verbose_name='Área habitable (sqft)'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_lot',
            field=models.PositiveIntegerField(verbose_name='Área del terreno (sqft)'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='view_c',
            field=models.PositiveIntegerField(default=0, verbose_name='Vista'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='waterfront',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='Frente al agua'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='yr_built',
            field=models.PositiveIntegerField(verbose_name='Año de construcción'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='yr_renovated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de renovación'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
