# Generated by Django 5.1.2 on 2024-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_casas_app', '0003_alter_casas_usuario_fk_alter_casas_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casas',
            options={},
        ),
        migrations.RemoveField(
            model_name='casas',
            name='view_c',
        ),
        migrations.AddField(
            model_name='casas',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casas',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casas',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='condition',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='casas',
            name='floors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='grade',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_above',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_basement',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_living',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_lot',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='waterfront',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Sí')], max_length=1),
        ),
        migrations.AlterField(
            model_name='casas',
            name='yr_built',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='casas',
            name='yr_renovated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casas',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='casas',
            table=None,
        ),
    ]
