# Generated by Django 5.1.2 on 2024-12-06 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_casas_app', '0004_alter_casas_options_remove_casas_view_c_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casas',
            name='bathrooms',
            field=models.PositiveIntegerField(verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='bedrooms',
            field=models.PositiveIntegerField(verbose_name='bedrooms'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='condition',
            field=models.PositiveIntegerField(default=3, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='floors',
            field=models.PositiveIntegerField(verbose_name='floors'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='grade',
            field=models.PositiveIntegerField(default=7, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Predicted Price'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_above',
            field=models.PositiveIntegerField(verbose_name='sqft_above'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_basement',
            field=models.PositiveIntegerField(verbose_name='sqft_basement'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_living',
            field=models.PositiveIntegerField(verbose_name='sqft_living'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='sqft_lot',
            field=models.PositiveIntegerField(verbose_name='sqft_lot'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casas',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='view'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='waterfront',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='waterfront'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='yr_built',
            field=models.PositiveIntegerField(verbose_name='yr_built'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='yr_renovated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='yr_renovated'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='zipcode'),
        ),
    ]
